import argparse
import json
import queue
import re
import shutil
import subprocess
import threading
from dataclasses import dataclass
from pathlib import Path
import tkinter as tk
from tkinter import filedialog, messagebox

APP_TITLE = "LN Bot Creator"


@dataclass
class GenerationInput:
    token: str
    feature_prompt: str
    output_dir: Path


class BotProjectGenerator:
    def __init__(self, log_func):
        self.log = log_func

    def generate(self, data: GenerationInput):
        project_name = self._derive_project_name(data.feature_prompt)
        project_dir = data.output_dir / project_name

        self.log("Analysiere Funktionen...")
        feature_flags = self._analyze_features(data.feature_prompt)

        self.log("Erstelle Projektstruktur...")
        self._create_directories(project_dir)

        self.log("Erstelle Konfigurationsdateien...")
        self._write_base_files(project_dir, data.token, feature_flags)

        self.log("Generiere Commands...")
        self._write_commands(project_dir, feature_flags)

        self.log("Generiere Events...")
        self._write_events(project_dir)

        self.log("Installiere Abhängigkeiten...")
        self._install_dependencies(project_dir)

        self.log(f"Bot erfolgreich erstellt: {project_dir}")
        return project_dir

    def _derive_project_name(self, prompt: str) -> str:
        tokens = re.findall(r"[a-zA-Z0-9]+", prompt.lower())
        core = "-".join(tokens[:4]) or "ln-discord-bot"
        return f"ln-bot-{core}"[:60]

    def _analyze_features(self, prompt: str):
        p = prompt.lower()
        return {
            "moderation": any(k in p for k in ["moderation", "mod", "ban", "kick"]),
            "tickets": any(k in p for k in ["ticket", "support"]),
            "music": "musik" in p or "music" in p,
            "logs": "log" in p,
            "welcome": any(k in p for k in ["begrü", "welcome", "join"]),
            "autorole": any(k in p for k in ["auto-rolle", "autorole", "rolle"]),
            "level": any(k in p for k in ["level", "xp"]),
        }

    def _create_directories(self, project_dir: Path):
        for rel in ["src", "src/commands", "src/events", "src/utils", "data"]:
            (project_dir / rel).mkdir(parents=True, exist_ok=True)

    def _write_base_files(self, project_dir: Path, token: str, features):
        (project_dir / ".env").write_text(f"DISCORD_TOKEN={token}\n", encoding="utf-8")

        package_json = {
            "name": project_dir.name,
            "version": "1.0.0",
            "description": "Generated by LN Bot Creator",
            "main": "src/index.js",
            "type": "commonjs",
            "scripts": {
                "start": "node src/index.js",
                "deploy": "node src/deploy-commands.js",
            },
            "engines": {"node": ">=18.0.0"},
            "dependencies": {
                "discord.js": "^14.16.3",
                "dotenv": "^16.4.5",
            },
        }

        (project_dir / "package.json").write_text(
            json.dumps(package_json, indent=2), encoding="utf-8"
        )

        config = {
            "clientId": "PUT_CLIENT_ID_HERE",
            "guildId": "PUT_TEST_GUILD_ID_HERE",
            "features": features,
        }
        (project_dir / "config.json").write_text(
            json.dumps(config, indent=2), encoding="utf-8"
        )

        (project_dir / "src/index.js").write_text(self._index_js(), encoding="utf-8")
        (project_dir / "src/deploy-commands.js").write_text(
            self._deploy_js(), encoding="utf-8"
        )
        (project_dir / "README.md").write_text(self._readme(features), encoding="utf-8")

    def _write_commands(self, project_dir: Path, features):
        commands_dir = project_dir / "src/commands"
        command_files = {
            "ping.js": self._cmd_ping(),
            "help.js": self._cmd_help(features),
        }

        if features["moderation"]:
            command_files["clear.js"] = self._cmd_clear()
        if features["tickets"]:
            command_files["ticket.js"] = self._cmd_ticket()
        if features["music"]:
            command_files["music.js"] = self._cmd_music_stub()
        if features["logs"]:
            command_files["setlog.js"] = self._cmd_setlog()
        if features["level"]:
            command_files["level.js"] = self._cmd_level()

        for name, content in command_files.items():
            (commands_dir / name).write_text(content, encoding="utf-8")

    def _write_events(self, project_dir: Path):
        events_dir = project_dir / "src/events"
        (events_dir / "ready.js").write_text(self._event_ready(), encoding="utf-8")
        (events_dir / "interactionCreate.js").write_text(
            self._event_interaction(), encoding="utf-8"
        )
        (events_dir / "guildMemberAdd.js").write_text(
            self._event_member_add(), encoding="utf-8"
        )

    def _install_dependencies(self, project_dir: Path):
        npm_path = shutil.which("npm")
        if not npm_path:
            self.log("npm nicht gefunden. Abhängigkeiten bitte manuell mit 'npm install' installieren.")
            return

        try:
            subprocess.run(
                [npm_path, "install"],
                cwd=project_dir,
                check=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                text=True,
            )
            self.log("Abhängigkeiten erfolgreich installiert.")
        except subprocess.CalledProcessError as exc:
            self.log("Warnung: npm install fehlgeschlagen. Ausgabe:")
            self.log(exc.stdout[-800:] if exc.stdout else "Keine Ausgabe vorhanden.")

    def _index_js(self):
        return """require('dotenv').config();
const fs = require('fs');
const path = require('path');
const { Client, Collection, GatewayIntentBits, Partials } = require('discord.js');

const client = new Client({
  intents: [
    GatewayIntentBits.Guilds,
    GatewayIntentBits.GuildMessages,
    GatewayIntentBits.GuildMembers,
    GatewayIntentBits.MessageContent,
  ],
  partials: [Partials.Channel],
});

client.commands = new Collection();

const commandsPath = path.join(__dirname, 'commands');
for (const file of fs.readdirSync(commandsPath).filter((file) => file.endsWith('.js'))) {
  const command = require(path.join(commandsPath, file));
  client.commands.set(command.data.name, command);
}

const eventsPath = path.join(__dirname, 'events');
for (const file of fs.readdirSync(eventsPath).filter((file) => file.endsWith('.js'))) {
  const event = require(path.join(eventsPath, file));
  if (event.once) {
    client.once(event.name, (...args) => event.execute(...args, client));
  } else {
    client.on(event.name, (...args) => event.execute(...args, client));
  }
}

if (!process.env.DISCORD_TOKEN) {
  console.error('DISCORD_TOKEN fehlt in .env');
  process.exit(1);
}

client.login(process.env.DISCORD_TOKEN);
"""

    def _deploy_js(self):
        return """require('dotenv').config();
const fs = require('fs');
const path = require('path');
const { REST, Routes } = require('discord.js');
const config = require('../config.json');

const commands = [];
const commandsPath = path.join(__dirname, 'commands');
for (const file of fs.readdirSync(commandsPath).filter((file) => file.endsWith('.js'))) {
  const command = require(path.join(commandsPath, file));
  commands.push(command.data.toJSON());
}

const rest = new REST({ version: '10' }).setToken(process.env.DISCORD_TOKEN);

(async () => {
  try {
    console.log(`Registriere ${commands.length} Slash-Commands ...`);
    await rest.put(
      Routes.applicationGuildCommands(config.clientId, config.guildId),
      { body: commands },
    );
    console.log('Slash-Commands erfolgreich registriert.');
  } catch (error) {
    console.error(error);
  }
})();
"""

    def _event_ready(self):
        return """const { Events } = require('discord.js');

module.exports = {
  name: Events.ClientReady,
  once: true,
  execute(client) {
    console.log(`[READY] ${client.user.tag} ist online.`);
  },
};
"""

    def _event_interaction(self):
        return """const { Events } = require('discord.js');

module.exports = {
  name: Events.InteractionCreate,
  async execute(interaction, client) {
    if (!interaction.isChatInputCommand()) return;

    const command = client.commands.get(interaction.commandName);
    if (!command) return;

    try {
      await command.execute(interaction, client);
    } catch (error) {
      console.error(error);
      const content = 'Fehler bei der Ausführung des Commands.';
      if (interaction.replied || interaction.deferred) {
        await interaction.followUp({ content, ephemeral: true });
      } else {
        await interaction.reply({ content, ephemeral: true });
      }
    }
  },
};
"""

    def _event_member_add(self):
        return """const { Events } = require('discord.js');
const config = require('../../config.json');

module.exports = {
  name: Events.GuildMemberAdd,
  async execute(member) {
    if (!config.features.welcome) return;

    const defaultChannel = member.guild.systemChannel;
    if (defaultChannel) {
      await defaultChannel.send(`Willkommen ${member.user}!`);
    }

    if (config.features.autorole) {
      const role = member.guild.roles.cache.find((r) => r.name.toLowerCase().includes('member'));
      if (role) {
        await member.roles.add(role).catch(() => {});
      }
    }
  },
};
"""

    def _cmd_ping(self):
        return """const { SlashCommandBuilder } = require('discord.js');

module.exports = {
  data: new SlashCommandBuilder().setName('ping').setDescription('Antwortet mit Pong!'),
  async execute(interaction) {
    await interaction.reply('Pong! 🏓');
  },
};
"""

    def _cmd_help(self, features):
        enabled = [k for k, v in features.items() if v]
        features_line = ", ".join(enabled) if enabled else "Basisbefehle"
        return f"""const {{ SlashCommandBuilder }} = require('discord.js');

module.exports = {{
  data: new SlashCommandBuilder().setName('help').setDescription('Zeigt aktive Bot-Funktionen an'),
  async execute(interaction) {{
    await interaction.reply(`Aktive Features: {features_line}`);
  }},
}};
"""

    def _cmd_clear(self):
        return """const { SlashCommandBuilder, PermissionFlagsBits } = require('discord.js');

module.exports = {
  data: new SlashCommandBuilder()
    .setName('clear')
    .setDescription('Löscht eine Anzahl Nachrichten')
    .addIntegerOption((o) => o.setName('anzahl').setDescription('Anzahl 1-100').setRequired(true))
    .setDefaultMemberPermissions(PermissionFlagsBits.ManageMessages),
  async execute(interaction) {
    const amount = interaction.options.getInteger('anzahl');
    await interaction.channel.bulkDelete(amount, true);
    await interaction.reply({ content: `Gelöscht: ${amount}`, ephemeral: true });
  },
};
"""

    def _cmd_ticket(self):
        return """const { SlashCommandBuilder, ChannelType, PermissionFlagsBits } = require('discord.js');

module.exports = {
  data: new SlashCommandBuilder().setName('ticket').setDescription('Erstellt ein Support-Ticket'),
  async execute(interaction) {
    const channel = await interaction.guild.channels.create({
      name: `ticket-${interaction.user.username}`,
      type: ChannelType.GuildText,
      permissionOverwrites: [
        {
          id: interaction.guild.id,
          deny: [PermissionFlagsBits.ViewChannel],
        },
        {
          id: interaction.user.id,
          allow: [PermissionFlagsBits.ViewChannel, PermissionFlagsBits.SendMessages],
        },
      ],
    });

    await channel.send(`Hallo ${interaction.user}, dein Ticket wurde erstellt.`);
    await interaction.reply({ content: `Ticket erstellt: ${channel}`, ephemeral: true });
  },
};
"""

    def _cmd_music_stub(self):
        return """const { SlashCommandBuilder } = require('discord.js');

module.exports = {
  data: new SlashCommandBuilder().setName('music').setDescription('Info zum Musik-Modul'),
  async execute(interaction) {
    await interaction.reply('Musik-Feature vorbereitet. Für Wiedergabe bitte @discordjs/voice + player integrieren.');
  },
};
"""

    def _cmd_setlog(self):
        return """const { SlashCommandBuilder, PermissionFlagsBits } = require('discord.js');

module.exports = {
  data: new SlashCommandBuilder()
    .setName('setlog')
    .setDescription('Setzt den aktuellen Kanal als Log-Kanal')
    .setDefaultMemberPermissions(PermissionFlagsBits.Administrator),
  async execute(interaction) {
    await interaction.reply({ content: 'Log-Kanal gesetzt (Persistenz kann in config ergänzt werden).', ephemeral: true });
  },
};
"""

    def _cmd_level(self):
        return """const { SlashCommandBuilder } = require('discord.js');

module.exports = {
  data: new SlashCommandBuilder().setName('level').setDescription('Zeigt dein aktuelles Level'),
  async execute(interaction) {
    await interaction.reply('Levelsystem vorbereitet. Speichere XP z. B. in sqlite oder redis.');
  },
};
"""

    def _readme(self, features):
        active = [k for k, v in features.items() if v]
        return f"""# Discord Bot (Generated by LN Bot Creator)

## Aktive Features
{', '.join(active) if active else 'Basisfunktionen'}

## Setup
1. `.env` enthält bereits den Bot Token.
2. `config.json` mit `clientId` und `guildId` füllen.
3. Abhängigkeiten installieren: `npm install`
4. Slash Commands deployen: `npm run deploy`
5. Bot starten: `npm start`
"""


class LNBotCreatorApp:
    def __init__(self, root):
        self.root = root
        root.title(APP_TITLE)
        root.geometry("900x620")
        root.configure(bg="#0d1117")

        self.queue = queue.Queue()
        self.generator = BotProjectGenerator(self.log)

        self.status_text = tk.StringVar(value="Bereit")

        self._build_ui()
        self._poll_queue()

    def _build_ui(self):
        font_main = ("Cascadia Mono", 11)
        font_title = ("Cascadia Mono", 18, "bold")

        frame = tk.Frame(self.root, bg="#0d1117", padx=20, pady=20)
        frame.pack(fill="both", expand=True)

        tk.Label(
            frame,
            text="LN Bot Creator",
            fg="#58a6ff",
            bg="#0d1117",
            font=font_title,
            anchor="w",
        ).pack(fill="x")

        tk.Label(
            frame,
            text="Willkommen bei LN Bot Creator\nDieses Tool erstellt automatisch deinen Discord-Bot.",
            fg="#c9d1d9",
            bg="#0d1117",
            font=font_main,
            justify="left",
            anchor="w",
        ).pack(fill="x", pady=(10, 18))

        self.token_entry = self._entry_block(
            frame,
            "1) Discord Bot Token",
            "Token wird lokal in der .env-Datei des generierten Projekts gespeichert.",
            show="*",
        )

        self.prompt_text = self._text_block(
            frame,
            "2) Bot-Prompt / gewünschte Funktionen",
            "Beschreibe in natürlicher Sprache, was dein Bot können soll (Moderation, Tickets, Logs, ...).",
        )

        output_row = tk.Frame(frame, bg="#0d1117")
        output_row.pack(fill="x", pady=(16, 6))
        tk.Label(output_row, text="3) Zielordner", fg="#8b949e", bg="#0d1117", font=font_main).pack(side="left")

        self.output_var = tk.StringVar(value=str(Path.cwd()))
        tk.Entry(
            output_row,
            textvariable=self.output_var,
            bg="#161b22",
            fg="#c9d1d9",
            insertbackground="#c9d1d9",
            relief="flat",
            font=font_main,
        ).pack(side="left", fill="x", expand=True, padx=8)
        tk.Button(
            output_row,
            text="...",
            command=self._choose_dir,
            bg="#21262d",
            fg="#c9d1d9",
            relief="flat",
            width=4,
        ).pack(side="left")

        controls = tk.Frame(frame, bg="#0d1117")
        controls.pack(fill="x", pady=(12, 8))
        self.generate_button = tk.Button(
            controls,
            text="Enter ↵  |  Bot automatisch erstellen",
            command=self.start_generation,
            bg="#238636",
            fg="#ffffff",
            relief="flat",
            font=("Cascadia Mono", 11, "bold"),
            padx=12,
            pady=8,
        )
        self.generate_button.pack(side="left")

        tk.Label(
            controls,
            textvariable=self.status_text,
            fg="#8b949e",
            bg="#0d1117",
            font=font_main,
        ).pack(side="right")

        self.log_box = tk.Text(
            frame,
            bg="#010409",
            fg="#7ee787",
            insertbackground="#7ee787",
            relief="flat",
            font=font_main,
            height=16,
            wrap="word",
        )
        self.log_box.pack(fill="both", expand=True, pady=(8, 0))
        self.log("[Bereit] Bitte Token + Feature-Prompt eingeben.")

        self.root.bind("<Return>", lambda _event: self.start_generation())

    def _entry_block(self, parent, title, subtitle, show=None):
        frame = tk.Frame(parent, bg="#0d1117")
        frame.pack(fill="x", pady=(0, 12))
        tk.Label(frame, text=title, fg="#8b949e", bg="#0d1117", font=("Cascadia Mono", 11)).pack(anchor="w")
        tk.Label(frame, text=subtitle, fg="#6e7681", bg="#0d1117", font=("Cascadia Mono", 9)).pack(anchor="w")
        entry = tk.Entry(
            frame,
            bg="#161b22",
            fg="#c9d1d9",
            insertbackground="#c9d1d9",
            relief="flat",
            font=("Cascadia Mono", 11),
            show=show,
        )
        entry.pack(fill="x", pady=(6, 0), ipady=8)
        return entry

    def _text_block(self, parent, title, subtitle):
        frame = tk.Frame(parent, bg="#0d1117")
        frame.pack(fill="x")
        tk.Label(frame, text=title, fg="#8b949e", bg="#0d1117", font=("Cascadia Mono", 11)).pack(anchor="w")
        tk.Label(frame, text=subtitle, fg="#6e7681", bg="#0d1117", font=("Cascadia Mono", 9)).pack(anchor="w")
        text = tk.Text(
            frame,
            bg="#161b22",
            fg="#c9d1d9",
            insertbackground="#c9d1d9",
            relief="flat",
            font=("Cascadia Mono", 11),
            height=5,
        )
        text.pack(fill="x", pady=(6, 0))
        return text

    def _choose_dir(self):
        chosen = filedialog.askdirectory(initialdir=self.output_var.get() or str(Path.cwd()))
        if chosen:
            self.output_var.set(chosen)

    def log(self, text):
        self.log_box.insert("end", f"> {text}\n")
        self.log_box.see("end")

    def _threadsafe_log(self, text):
        self.queue.put(("log", text))

    def _poll_queue(self):
        try:
            while True:
                action, payload = self.queue.get_nowait()
                if action == "log":
                    self.log(payload)
                elif action == "done":
                    self.status_text.set("Bereit")
                    self.generate_button.configure(state="normal")
                    messagebox.showinfo(APP_TITLE, f"Fertig! Projekt erstellt unter:\n{payload}")
                elif action == "error":
                    self.status_text.set("Fehler")
                    self.generate_button.configure(state="normal")
                    messagebox.showerror(APP_TITLE, payload)
        except queue.Empty:
            pass
        self.root.after(120, self._poll_queue)

    def start_generation(self):
        token = self.token_entry.get().strip()
        prompt = self.prompt_text.get("1.0", "end").strip()
        out = Path(self.output_var.get().strip() or Path.cwd())

        if not token or not prompt:
            messagebox.showwarning(APP_TITLE, "Bitte Token und Feature-Prompt ausfüllen.")
            return
        if not out.exists():
            messagebox.showwarning(APP_TITLE, "Der Zielordner existiert nicht.")
            return

        self.generate_button.configure(state="disabled")
        self.status_text.set("Erstelle Dateien...")
        self.log("Starte automatische Bot-Erstellung ...")

        def worker():
            try:
                local_generator = BotProjectGenerator(self._threadsafe_log)
                result = local_generator.generate(
                    GenerationInput(token=token, feature_prompt=prompt, output_dir=out)
                )
                self.queue.put(("done", str(result)))
            except Exception as exc:  # broad catch to keep UI responsive
                self.queue.put(("error", f"Bot-Erstellung fehlgeschlagen: {exc}"))

        threading.Thread(target=worker, daemon=True).start()


def run_self_test():
    from tempfile import TemporaryDirectory

    print('[SELF-TEST] Starte Generator-Testlauf ...')

    with TemporaryDirectory() as tmp:
        output = Path(tmp)
        generator = BotProjectGenerator(print)
        project = generator.generate(
            GenerationInput(
                token='TEST_TOKEN',
                feature_prompt='Moderation, Tickets, Logs, Begrüßung, Levelsystem',
                output_dir=output,
            )
        )
        checks = [
            project / 'package.json',
            project / 'config.json',
            project / '.env',
            project / 'src/index.js',
            project / 'src/events/interactionCreate.js',
            project / 'src/commands/ping.js',
        ]
        missing = [str(c) for c in checks if not c.exists()]
        if missing:
            print('[SELF-TEST] FEHLER: Dateien fehlen:')
            for item in missing:
                print(' -', item)
            return 1

    print('[SELF-TEST] OK: Projektstruktur und Dateien wurden erstellt.')
    return 0


def main():
    parser = argparse.ArgumentParser(description='LN Bot Creator')
    parser.add_argument('--self-test', action='store_true', help='Führt einen nicht-interaktiven Generator-Testlauf aus.')
    args = parser.parse_args()

    if args.self_test:
        raise SystemExit(run_self_test())

    root = tk.Tk()
    LNBotCreatorApp(root)
    root.mainloop()


if __name__ == "__main__":
    main()
